kind: AIchorManifest 
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./Dockerfile
  context: .   
  buildArgs:  
    JFROG_BASE_REPOSITORY: aichor-dev-docker
    JFROG_URL: artifactory.bion.tech

spec:    
  operator: tf   
  image: image   
  command: "python3 -u main.py --operator=tf --sleep=43200 --tb-write=true"  
   
  tensorboard: 
    enabled: true
    
  types: 
    Worker: 
      count: 1  
      resources: 
        cpus: 1 
        ramRatio: 2 
        shmSizeGB: 0
        accelerators: # optional
          gpu: 
            count: 0   
            type: gpu 
            product: a10g
